# Generated by Django 3.2.9 on 2021-12-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211207_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('anioFund', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='direccion',
            new_name='ciudad',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='anioFund',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
