# Generated by Django 3.2.9 on 2021-12-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_auto_20211207_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ciudad',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
